apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: bastilia-rating
  name: bastilia-rating
spec:
  replicas: 1 # Чтобы сделать две, надо решить вопрос с AspNet Data Protection
  selector:
    matchLabels:
      app.kubernetes.io/name: bastilia-rating
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bastilia-rating
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - bastilia-rating
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - name: bastilia-rating
        envFrom:
        - secretRef:
            name: bastilia-rating-secret
            optional: false
        - configMapRef:
            name: bastilia-rating-config
            optional: false
        image: bastilia-rating
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /health/live
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /health/ready
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 200m
            memory: 128Mi
